src/main/java/pl/wsti/gut/blog/model/Comment.java
package pl.wsti.gut.blog.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;

@Entity
public class Comment {
	@Id
	@GeneratedValue
	private Long id;

	@NotEmpty
	@Length(max=512)
	@Column(length = 512)
	private String content;

	@ManyToOne
	Post post;

	@OneToOne
	private User user;

	@Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime")
	private DateTime createDate;

	public Comment() {
		createDate = new DateTime();
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Post getPost() {
		return post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public DateTime getCreateDate() {
		return createDate;
	}

	public void setCreateDate(DateTime createDate) {
		this.createDate = createDate;
	}

	public String getLocalDateString() {
		return new LocalDate(createDate).toString();
	}
}

src/main/java/pl/wsti/gut/blog/model/Post.java
package pl.wsti.gut.blog.model;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.NotEmpty;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
public class Post {

	@Id
	@GeneratedValue
	private Long id;
	@NotEmpty
	@Lob
	private String content;
	@Column(nullable = false)
	@Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime")
	private DateTime createDate;
	@ManyToOne
	private User user;
	@ManyToOne(cascade = CascadeType.ALL)
	private Category category;
	@JsonIgnore
	@OneToMany(mappedBy = "post", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	private List<Photo> photos;
	@JsonIgnore
	@OneToMany(mappedBy = "post", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private List<Comment> comments;
	@NotEmpty
	private String title;

	public Post() {
		createDate = new DateTime();
		System.out.println(createDate);
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public DateTime getCreateDate() {
		return createDate;
	}

	public void setCreateDate(DateTime createDate) {
		this.createDate = createDate;
	}

	//
	// public List<Photo> getPhotos() {
	// return photos;
	// }
	//
	// public void setPhotos(List<Photo> photos) {
	// this.photos = photos;
	// }

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	public LocalDate getLocalDate() {
		return new LocalDate(createDate);
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}

src/main/java/pl/wsti/gut/blog/model/User.java
package pl.wsti.gut.blog.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;
import org.neo4j.cypher.internal.compiler.v2_1.planner.logical.steps.uniqueIndexSeekLeafPlanner;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import pl.wsti.gut.blog.common.Utility;

@Entity
@Component("user")
public class User {

	public enum Role {
		USER, ADMIN;
	}

	@NotEmpty
	@Column(unique = true)
	private String nick;
	@NotEmpty
	private String password;
	@NotEmpty
	@Transient
	private String passwordConfirm;
	@NotEmpty
	@Email
	@Column(unique = true)
	private String email;
	private String ggNo;
	private String wwwAddress;
	@Id
	@GeneratedValue
	private Long id;
	@Enumerated(EnumType.STRING)
	private Role role;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNick() {
		return nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGgNo() {
		return ggNo;
	}

	public void setGgNo(String ggNo) {
		this.ggNo = ggNo;
	}

	public String getWwwAddress() {
		return wwwAddress;
	}

	public void setWwwAddress(String wwwAddress) {
		this.wwwAddress = wwwAddress;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = Utility.hashWithMD5(password);
	}

	public String getPasswordConfirm() {
		return passwordConfirm;
	}

	public void setPasswordConfirm(String passwordConfirm) {
		this.passwordConfirm = Utility.hashWithMD5(passwordConfirm);
	}

	@PrePersist
	public void prePersist() {
		if (getRole() == null)
			setRole(Role.USER);
	}

}

src/main/java/pl/wsti/gut/blog/controller/LoginController.java
package pl.wsti.gut.blog.controller;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.validation.ObjectError;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import pl.wsti.gut.blog.model.User;
import pl.wsti.gut.blog.model.UserTemplate;
import pl.wsti.gut.blog.service.UserService;
import pl.wsti.gut.blog.view.UserValidator;

@Controller
public class LoginController {

	@Autowired
	UserService userService;

	@RequestMapping(value = "/login", method = RequestMethod.GET)
	public String showLoginWindow(Model model, HttpSession session) {

		UserTemplate user = (UserTemplate) session.getAttribute("userTemplate");
		if (user == null) {
			user = new UserTemplate();
		} else {
			user.setPassword("");
		}
		model.addAttribute("userTemplate", user);
		return "login";
	}

	@RequestMapping(value = "/login", method = RequestMethod.POST)
	public String verifyUser(
			@Valid @ModelAttribute("userTemplate") UserTemplate userTemplate,
			BindingResult result, HttpSession session) {

		User user = userService.findUserIfExists(userTemplate);
		if (user == null || result.hasErrors()) {
			ObjectError error = new ObjectError("login", "Zły nick lub hasło!");
			result.addError(error);
			return "login";
		} else {
			session.setAttribute("user", user);
			return "redirect:index.html";
		}

	}

}

src/main/java/pl/wsti/gut/blog/controller/PostController.java
package pl.wsti.gut.blog.controller;

import java.util.List;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import pl.wsti.gut.blog.model.Category;
import pl.wsti.gut.blog.model.Post;
import pl.wsti.gut.blog.model.User;
import pl.wsti.gut.blog.service.CategoryService;
import pl.wsti.gut.blog.service.PostService;

@Controller
public class PostController {

	@Autowired
	PostService postService;
	
	@Autowired
	CategoryService categoryService;
	
	User user;
	
	@RequestMapping(value = "/post", method = RequestMethod.GET)
	public String showPostForm(Model model, HttpSession session) {
		
		user = (User) session.getAttribute("user");
		if (user==null){
			return "redirect:index.html";
		}
		Post post = (Post) session.getAttribute("post");
		if (post == null) {
			post = new Post();
		}
		model.addAttribute("post", post);
		List<Category> categories = categoryService.findAll();
		model.addAttribute("categories", categories);

		return "post";
	}

	@RequestMapping(value = "/post", method = RequestMethod.POST)
	public String addPost(@Valid Post post, BindingResult result) {
		if (result.hasErrors()) {
			return "post";
		} else {
			post.setUser(user);
			postService.addPost(post);
		}
		return "redirect:index.html";
	}
	
	@RequestMapping(value = "/deletePost", method = RequestMethod.POST)
	public String deletePost(Post post) {
		
		//TODO
		postService.deletePost(post);
		return "index.html";
	}
}

src/main/java/pl/wsti/gut/blog/controller/UserController.java
package pl.wsti.gut.blog.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpRequest;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import pl.wsti.gut.blog.model.Email;
import pl.wsti.gut.blog.model.EmailSender;
import pl.wsti.gut.blog.model.User;
import pl.wsti.gut.blog.model.User.Role;
import pl.wsti.gut.blog.service.UserService;
import pl.wsti.gut.blog.view.UserValidator;

@Controller
public class UserController {

	@Autowired
	UserService userService;
	@Autowired
	Email email;
	@Autowired
	UserValidator userValidator;
	User user;

	@RequestMapping(value = "/user", method = RequestMethod.GET)
	public String showUserForm(Model model, HttpSession session) {

		// user = (User) session.getAttribute("user");
		// if (user == null || user.getRole() != Role.ADMIN) {
		// return "redirect:index.html";
		// }
		User newUser = (User) session.getAttribute("newUser");
		if (newUser == null) {
			newUser = new User();
		}
		model.addAttribute("newUser", newUser);

		return "user";
	}

	@RequestMapping(value = "/user", method = RequestMethod.POST)
	public String addUser(@Valid @ModelAttribute("newUser") User newUser,
			BindingResult result, HttpServletRequest request) {

		userValidator.validate(newUser, result);
		if (result.hasErrors()) {
			return "user";
		} else {
			userService.addUser(newUser);
			email.setRecipient(newUser);
			email.setSubject("Witaj na blogu WSTI");
			email.setContent(String.format(
					"Twój nick: %1s\n\nPozdrawiam,\nMichał Gut",
					newUser.getNick()));
			email.send();
			String referrer = request.getHeader("referer");
			if (referrer.contains("admin")) {
				return "redirect:admin.html";
			}
			return "redirect:index.html";
		}
	}

}

src/main/webapp/WEB-INF/jsp/admin.jsp
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<!doctype html>
<html ng-app class="no-js" lang="pl"
	data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Blog WSTI</title>
<script
	src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"></script>
<%@ include file="/WEB-INF/jsp/items/scirptsAndStyles.jsp"%>
<script src="js/restControllers/admin.js"></script>
</head>
<body>

	<%@ include file="/WEB-INF/jsp/items/label.jsp"%>

	<div class="row">
		<div class="large-8 columns">
			<h3>Użytkownicy</h3>
		</div>
	</div>
	<div class="row" ng-controller="UserController">
		<div class="large-8 columns">
			<table style="width: 100%">
				<!-- 				<tr>
					<th columnspan="2">Nick</th>
					<th columnspan="2">e-mail</th>
					<th><div style="text-align: center;">
							<img src="img/email.png" height="42" width="42">
						</div> <select ng-options="item in userGroups"></select></th>
					<th>
						<div style="text-align: center;">
							<img src="img/delete-user.jpg" height="42" width="42">
						</div> <select></select>
					</th>
				</tr> -->
				<tr>
					<th>Nick</th>
					<th>e-mail</th>
					<th><img src="img/email.png" height="36" width="36"></th>
					<th><img src="img/delete-user.jpg" height="36" width="36">
					</th>
				</tr>
				<tr ng-repeat="user in users">
					<td>{{user.nick}}</td>
					<td>{{user.email}}</td>
					<td><input type="checkbox" ng-model="addUserValue"
						ng-change="addUserToEmail(user,addUserValue)" /></td>
					<td><input type="checkbox" ng-model="deleteUserValue"
						ng-change="addUserToUsersToDelete(user,deleteUserValue)"></td>
				</tr>
				<tr>
					<td rowspan="1">
						<button class="button" ng-click="deleteUsers()">Usuń
							wybranych uzytkowników</button>
					</td>
				</tr>
			</table>
		</div>
		<div class="large-4 columns panel">
			<h6>Wyślij wiadomość</h6>
			<div>
				<label>Tytuł:</label> <input ng-model="email.subject" type="text" />
				<label>Treść:</label>
				<textarea rows="7" ng-model="email.content"></textarea>
				<button class="button" ng-click="send(email)">Wyślij</button>
				<br>
			</div>
		</div>
		<div class="large-4 columns panel">
			<h4>
				<a href="user.html" class="button ">Dodaj nowego użytkownika</a>
			</h4>
		</div>
	</div>
	<div class="row">
		<hr>
		<div ng-controller="CategoryController" class="large-12 columns">
			<h3>Kategorie</h3>
			<div class="row collapse">
				<div class="large-8 small-9 columns">
					<input ng-model="category.name" type="text"
						placeholder="Dodaj kategorię" />
				</div>
				<div class="large-4 small-3 columns ">
					<a ng-click="addCategory(category)" class="button ">Dodaj</a>
				</div>
			</div>

			<div class="row collapse" ng-repeat="category in categories">
				<div class="large-8 small-9 columns">
					<label class="panel">{{category.name}}</label>
				</div>
				<div class="large-4 small-3 columns ">
					<button ng-click="deleteCategory(category)">Usuń</button>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<br> <br>
		<p />
		<a href="index.html">Powrót do strony głównej</a>
	</div>
	<%@ include file="/WEB-INF/jsp/items/footer.jsp"%>
</body>
</html>

src/main/webapp/WEB-INF/jsp/index.jsp
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<!doctype html>
<html ng-app class="no-js" lang="pl"
	data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Blog WSTI</title>
<%@ include file="/WEB-INF/jsp/items/scirptsAndStyles.jsp"%>
<script
	src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"></script>
<script src="js/restControllers/comments.js"></script>
</head>
<body>
	<%@ include file="/WEB-INF/jsp/items/label.jsp"%>
	<div class="row">
		<div class="large-9 columns" role="content">
			<c:forEach items="${posts}" var="post" varStatus="postLoop">
				<article ng-init="postId = ${post.id};">

					<h3>
						<a href="#"><c:out value="${post.title}" /></a>
					</h3>
					<h6>
						Dodane przez <a href="#">${post.user.nick}</a> w dniu
						${post.localDate}
					</h6>
					<h6>
						Kategoria: <a href="#">${post.category.name}</a>
					</h6>
					<div class="row">
						<div class="large-12 columns">
							<p>${post.content}</p>
						</div>
						<div class="large-6 columns">
							<c:forEach begin="0" end="9" varStatus="loop">
								<%-- <img src="img/0${loop.index}.jpg" /> --%>
								<%-- <img src="img/0${loop.index}.jpg" height="64" width="64" /> --%>
							</c:forEach>
						</div>
					</div>
					<br>
					<div class="panel" ng-controller="CommentController">
						<h4>Komentarze</h4>
						<c:choose>
							<c:when test="${!empty sessionScope.user}">
								<form novalidate>
									Dodaj komentarz:<br>
									<textarea rows="5" ng-model="comment.content"></textarea>
									<br>
									<button ng-click="add(${post.id})">Dodaj</button>
								</form>
							</c:when>
						</c:choose>
						<div class="comments-container">
							<div ng-repeat="comment in comments">
								<h6 class="subheader">
									Dodane przez <a href="#">{{comment.user.nick}}</a> w dniu
									{{comment.localDateString}}.
								</h6>
								<p>{{comment.content}}</p>
								<hr ng-hide="$last">
							</div>
						</div>
						<!-- <a href="#">Read More &rarr;</a> -->
					</div>
				</article>
				<c:if test="${fn:length(posts)-1>postLoop.index}">

					<hr />
				</c:if>
			</c:forEach>
			<!-- 			<article>
				<h3>
					<a href="#">Blog Post Title</a>
				</h3>
				<h6>
					Dodane przez <a href="#">Michał Gut</a> w dniu 01-09-2015.
				</h6>
				<div class="row">
					<div class="large-6 columns">
						<p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation
							eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore
							aliqua non est magna in labore pig pork biltong. Eiusmod swine
							spare ribs reprehenderit culpa.</p>
						<p>Boudin aliqua adipisicing rump corned beef. Nulla corned
							beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs
							minim salami nulla nostrud pastrami.</p>
					</div>
					<div class="large-6 columns">
						<img src="http://placehold.it/400x240&text=[img]" />
					</div>
				</div>
				<p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork
					chop in. Swine short ribs meatball irure bacon nulla pork belly
					cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui
					bresaola enim jowl. Capicola short ribs minim salami nulla nostrud
					pastrami. Nulla corned beef sunt ball tip, qui bresaola enim jowl.
					Capicola short ribs minim salami nulla nostrud pastrami.</p>
				<p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork
					chop in. Swine short ribs meatball irure bacon nulla pork belly
					cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui
					bresaola enim jowl. Capicola short ribs minim salami nulla nostrud
					pastrami.</p>
			</article>-->
		</div>


		<aside class="large-3 columns">
			<div class="panel">
				<h5>Kategorie</h5>
				<ul class="side-nav">
					<li><a href="index.html?page=1">Wszystkie</a></li>
					<c:forEach var="category" items="${categories}">
						<li><a href="index.html?categoryId=${category.id}">${category.name}</a></li>
					</c:forEach>
				</ul>
			</div>
		</aside>

	</div>


	<footer class="row">
		<div class="large-12 columns">
			<div class="row">
				<div class="large-6 columns">
					<ul class="inline-list right">
						<li><c:if test="${param.page>1}">
								<a href="index.html?page=${param.page-1}">Poprzednia strona</a>
							</c:if></li>
						<li><c:choose>
								<c:when test="${!last}">
									<a
										href="index.html?page=${param.page+1}&categoryId=${param.categoryId}">Następna
										strona</a>
								</c:when>
								<c:otherwise>
									<a style="display: none;"
										href="index.html?page=${param.page+1}&categoryId=${param.categoryId}">Następna
										strona</a>
								</c:otherwise>
							</c:choose></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<%@ include file="/WEB-INF/jsp/items/footer.jsp"%>
</body>
</html>

src/main/webapp/WEB-INF/jsp/login.jsp
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!doctype html>
<html class="no-js" lang="pl"
	data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Blog WSTI</title>
<%@ include file="/WEB-INF/jsp/items/scirptsAndStyles.jsp"%>
</head>
<body>
	<div class="row large-6 columns small-centered">
		<div class="panel" role="content">
			<h1>Zaloguj się</h1>
			<form:form commandName="userTemplate">
				<form:errors path="${login}" cssClass="errorblock" element="div" />
				<label>Login:</label>
				<form:input path="nick" cssErrorClass="error" />
				<form:errors path="nick" cssClass="error" />
				<label>Hasło:</label>
				<form:password path="password" cssErrorClass="error" />
				<form:errors path="password" cssClass="error" />
				<input type="submit" class="button" value="Zaloguj" />
				<br>
			</form:form>
			<a href="user.html">Nie masz konta? Zarejestruj się</a>
		</div>
		<br> <br> <a href="index.html">Powrót do strony głównej</a>
	</div>
	<p></p>
	<%@ include file="/WEB-INF/jsp/items/footer.jsp"%>
</body>
</html>

src/main/webapp/WEB-INF/jsp/post.jsp
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!doctype html>
<html class="no-js" lang="pl"
	data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Blog WSTI</title>
<%@ include file="/WEB-INF/jsp/items/scirptsAndStyles.jsp"%>
</head>
<body>
	<div class="row large-6 columns small-centered" >
		<div role="content">
			<h1>Dodaj post</h1>
			<form:form commandName="post">
				<label>Tytuł:</label>
				<form:input path="title" cssErrorClass="error" />
				<form:errors path="title" cssClass="error" />
				<label>Kategoria:</label>
				<form:select path="category" cssErrorClass="error">
					<form:options items="${categories}" itemValue="id" itemLabel="name" />
				</form:select>
				<form:errors path="title" cssClass="error" />
				<label>Treść posta:</label>
				<form:textarea style="height: 250px;" path="content"
					cssErrorClass="error" />
				<form:errors path="content" cssClass="error" />
				<input type="submit" class="button" value="Dodaj post" />
				<br>
			</form:form>
			<br> <br> <a href="index.html">Powrót do strony głównej</a>
		</div>
	</div>
	<p></p>
	<%@ include file="/WEB-INF/jsp/items/footer.jsp"%>
</body>
</html>

src/main/webapp/WEB-INF/jsp/user.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!doctype html>
<html class="no-js" lang="pl"
	data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Blog WSTI</title>
<%@ include file="/WEB-INF/jsp/items/scirptsAndStyles.jsp"%>
</head>
<body>
	<div class="row large-6 columns small-centered">
		<div role="content">
			<h1>Dodaj użytkownika</h1>
			<form:form commandName="newUser">
				<div class="panel">
					<label>Nick:</label>
					<form:input path="nick" cssErrorClass="error" />
					<form:errors path="nick" cssClass="error" />
					<label>Hasło:</label>
					<form:password path="password" cssErrorClass="error" />
					<form:errors path="password" cssClass="error" />
					<label>Potwierdź hasło:</label>
					<form:password path="passwordConfirm" cssErrorClass="error" />
					<form:errors path="passwordConfirm" cssClass="error" />
				</div>
				<div class="panel">
					<label>E-Mail:</label>
					<form:input path="email" cssErrorClass="error" />
					<form:errors path="email" cssClass="error" />
					<label>Numer GG:</label>
					<form:input path="ggNo" cssErrorClass="error" />
					<form:errors path="ggNo" cssClass="error" />
					<label>Adres WWW:</label>
					<form:input path="wwwAddress" cssErrorClass="error" />
					<form:errors path="wwwAddress" cssClass="error" />
					<c:if test="${sessionScope.user.role eq 'ADMIN'}">
						<label>Rola:</label>
						<form:select path="role">
							<form:option value="USER" label="User" />
							<form:option value="ADMIN" label="Admin" />
						</form:select>
					</c:if>
				</div>
				<input type="submit" class="button" value="Dodaj użytkownika" />
				<br>
			</form:form>
		</div>
		<br> <br> <a href="index.html">Powrót do strony głównej</a>
	</div>
	<p></p>
	<%@ include file="/WEB-INF/jsp/items/footer.jsp"%>
</body>
</html>